const data = {
  McProducts: [
    {
      _id: 1,
      name: "burger",
      img: "/images/mcproducts/mc(1).jpg",
      price: 7,
      category: "burger",
    },
    {
      _id: 2,
      name: "set burger",
      img: "/images/mcproducts/mc(2).png",
      price: 15,
      category: "burger",
    },
    {
      _id: 3,
      name: "double burger",
      img: "/images/mcproducts/mc(4).jpg",
      price: 7,
      category: "burger",
    },
    {
      _id: 4,
      name: " chicken burger",
      img: "/images/mcproducts/mc(5).jpg",
      price: 7,
      category: "burger",
    },
    {
      _id: 5,
      name: "fry",
      img: "/images/mcproducts/mc(7).jpg",
      price: 7,
      category: "burger",
    },
  ],
  KfcProducts: [
    {
      _id: 6,
      name: "Kfc chicken",
      img: "/images/kfcproducts/kfc(2).png",
      price: 7,
      category: "burger",
    },
    {
      _id: 7,
      name: "Kfc fry",
      img: "/images/kfcproducts/kfc(3).jpg",
      price: 7,
      category: "burger",
    },
    {
      _id: 8,
      name: "kfc nuggets",
      img: "/images/kfcproducts/kfc(5).png",
      price: 7,
      category: "burger",
    },
    {
      _id: 9,
      name: "Kfc chicken burger",
      img: "/images/kfcproducts/kfc(6).png",
      price: 7,
      category: "burger",
    },
    {
      _id: 10,
      name: "double chicken",
      img: "/images/kfcproducts/kfc(8).jpg",
      price: 7,
      category: "burger",
    },
    {
      _id: 11,
      name: "chicken legs",
      img: "/images/kfcproducts/kfc(9).png",
      price: 7,
      category: "burger",
    },
  ],
  PizzaProducts: [
    {
      _id: 12,
      name: "Regular Pizza",
      img: "/images/pizzaproducts/p(2).jpg",
      price: 7,
      category: "pizza",
    },
    {
      _id: 13,
      name: "Cheese Pizza",
      img: "/images/pizzaproducts/p(3).jpg",
      price: 7,
      category: "pizza",
    },
    {
      _id: 14,
      name: "Vegeterian Pizza",
      img: "/images/pizzaproducts/p(4).jpg",
      price: 7,
      category: "pizza",
    },
    {
      _id: 15,
      name: "Margarita",
      img: "/images/pizzaproducts/p(5).jpg",
      price: 7,
      category: "pizza",
    },
    {
      _id: 16,
      name: "Boss Pizza",
      img: "/images/pizzaproducts/p(6).jpg",
      price: 7,
      category: "pizza",
    },
    {
      _id: 17,
      name: "Sausage Pizza",
      img: "/images/pizzaproducts/p(7).png",
      price: 7,
      category: "pizza",
    },
  ],
  DrinksProducts: [
    {
      _id: 18,
      name: "Coca-Cola can",
      img: "/images/drinksproducts/d(1).jpg",
      price: 7,
      category: "drink",
    },
    {
      _id: 19,
      name: "Coca-Cola glass",
      img: "/images/drinksproducts/d(2).png",
      price: 7,
      category: "drink",
    },
    {
      _id: 20,
      name: "Coca-Cola gbottle",
      img: "/images/drinksproducts/d(3).png",
      price: 7,
      category: "drink",
    },
    {
      _id: 21,
      name: "Fanta can",
      img: "/images/drinksproducts/d(5).jpg",
      price: 7,
      category: "drink",
    },
    {
      _id: 22,
      name: "Fanta bottle",
      img: "/images/drinksproducts/d(6).jpg",
      price: 7,
      category: "drink",
    },
    {
      _id: 23,
      name: "Pepsi bottle",
      img: "/images/drinksproducts/d(7).jpg",
      price: 7,
      category: "drink",
    },
    {
      _id: 24,
      name: "Pepsi can",
      img: "/images/drinksproducts/d(9).jpg",
      price: 7,
      category: "drink",
    },
    {
      _id: 25,
      name: "Kompotlardi ichib",
      img: "/images/drinksproducts/d(10).jpg",
      price: 7,
      category: "drink",
    },
    {
      _id: 26,
      name: "3tasi birda",
      img: "/images/drinksproducts/d(11).png",
      price: 7,
      category: "drink",
    },
  ],
  BuggetBurgersProducts: [
    {
      _id: 27,
      name: "Burger Bugget",
      img: "/images/buggetsproducts/bug(1).jpg",
      price: 7,
      category: "burger",
    },
    {
      _id: 28,
      name: "Sausage Bugget",
      img: "/images/buggetsproducts/bug(2).jpg",
      price: 7,
      category: "burger",
    },
    {
      _id: 29,
      name: "Tomato Bugget",
      img: "/images/buggetsproducts/bug(3).png",
      price: 7,
      category: "burger",
    },
    {
      _id: 30,
      name: "Bugget Burger",
      img: "/images/buggetsproducts/bug(4).png",
      price: 7,
      category: "burger",
    },
    {
      _id: 31,
      name: "Double Bugget",
      img: "/images/buggetsproducts/bug(5).jpg",
      price: 7,
      category: "burger",
    },
    {
      _id: 32,
      name: "Chicken Bugget",
      img: "/images/buggetsproducts/bug(6).png",
      price: 7,
      category: "burger",
    },
    {
      _id: 33,
      name: "Cheese Bugget",
      img: "/images/buggetsproducts/bug(7).png",
      price: 7,
      category: "burger",
    },
  ],
  Menu: [
    {
      _id: 1,
      name: "McDonalds burgers",
      img: "/images/menu/mc.jpg",
      category: "b",
    },
    {
      _id: 2,
      name: "Kfc chickens",
      img: "/images/menu/kfc.png",
      category: "a",
    },
    {
      _id: 3,
      name: "Pizza",
      img: "/images/menu/pizza.jpg",
      category: "b",
    },
    {
      _id: 4,
      name: "Bugget burgers",
      img: "/images/menu/bugget.jpg",
      category: "a",
    },
    {
      _id: 5,
      name: "Drinks",
      img: "/images/menu/drinks.png",
      category: "c",
    },
  ],
};
module.exports = data;
